"""Add club_movies association table

Revision ID: 070a7755cbfb
Revises: 4a1a6d9ceabc
Create Date: 2024-11-30 17:21:05.753088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070a7755cbfb'
down_revision = '4a1a6d9ceabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_movies',
    sa.Column('ClubID', sa.Integer(), nullable=False),
    sa.Column('MovieID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ClubID'], ['clubs.ClubID'], ),
    sa.ForeignKeyConstraint(['MovieID'], ['movies.MovieID'], ),
    sa.PrimaryKeyConstraint('ClubID', 'MovieID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_movies')
    # ### end Alembic commands ###
