"""removed club_movies association table

Revision ID: 555b2bf14d8e
Revises: 070a7755cbfb
Create Date: 2024-11-30 17:28:52.264523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555b2bf14d8e'
down_revision = '070a7755cbfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_movies',
    sa.Column('ClubID', sa.INTEGER(), nullable=False),
    sa.Column('MovieID', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ClubID'], ['clubs.ClubID'], ),
    sa.ForeignKeyConstraint(['MovieID'], ['movies.MovieID'], ),
    sa.PrimaryKeyConstraint('ClubID', 'MovieID')
    )
    # ### end Alembic commands ###
