"""Add club_movies association table

Revision ID: ffe5ef3effd8
Revises: 555b2bf14d8e
Create Date: 2024-11-30 17:56:26.487000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe5ef3effd8'
down_revision = '555b2bf14d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_movies',
    sa.Column('ClubID', sa.Integer(), nullable=False),
    sa.Column('MovieID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ClubID'], ['clubs.ClubID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['MovieID'], ['movies.MovieID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ClubID', 'MovieID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_movies')
    # ### end Alembic commands ###
